# # 33080 和33081 映射到宿主机,方便调试
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: devcontainer-llm-chat-pod-export
#   labels:
#     app: devcontainer-llm-chat-pod-export
#   namespace: homeapp
# spec:
#   type: NodePort
#   ports:
#   - port: 30080
#     targetPort: 30080
#     nodePort: 30080
#     protocol: TCP
#     name: fe
#   - port: 30081
#     targetPort: 30081
#     nodePort: 30081
#     protocol: TCP
#     name: be
#   selector:
#     app: devcontainer